import json, html, pathlib
ROOT=pathlib.Path(__file__).resolve().parents[1]
data=json.loads((ROOT/'archive.json').read_text())
def e(s): return html.escape(str(s))
rows=[]
for q in data['teachings']:
 rows.append(f'''<article id="{e(q['id'])}"><div class="number">{q['order']:02d}</div><div><blockquote>{e(q['quote'])}</blockquote><p class="author">{e(q['author'])}</p><p class="credit">{e(q['work'])} · Translation: {e(q['translator'])}</p><details><summary>Source & context</summary><p>{e(q.get('context_note',''))}</p><p>{e(q['locator'])}</p><a href="{e(q['url'])}" rel="noopener noreferrer">Read the original source ↗</a><p class="credit">Verified {e(q['verified_date'])}. Translation rights remain with their respective holders.</p></details><a class="permalink" href="#{e(q['id'])}" aria-label="Link to teaching {q['order']}">§</a></div></article>''')
page='''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>For All Beings — A living Dharma library</title><meta name="description" content="Brief Buddhist teachings with exact wording, translator credits, and original sources."><link rel="icon" type="image/svg+xml" href="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 32 32'%3E%3Crect width='32' height='32' rx='16' fill='%23112738'/%3E%3Ccircle cx='16' cy='16' r='9' fill='none' stroke='%23f4bd54' stroke-width='2'/%3E%3C/svg%3E"><style>
:root{color-scheme:light;--ink:#112738;--muted:#52616b;--accent:#925514}*{box-sizing:border-box}html{scroll-behavior:smooth}body{margin:0;background:#fafbfc;color:var(--ink);font:18px/1.7 system-ui,sans-serif}header,main,footer{max-width:960px;margin:auto;padding:32px}nav{display:flex;justify-content:space-between;gap:24px;border-bottom:1px solid #b8c4cc;padding-bottom:20px;font-size:14px}a{color:inherit;text-underline-offset:4px}h1{font:clamp(3rem,8vw,5.5rem)/1.04 Georgia,serif;letter-spacing:-.045em;margin:48px 0 24px;max-width:650px}header>p{max-width:580px;color:var(--muted)}.eyebrow{text-transform:uppercase;letter-spacing:.16em;font-size:13px}.intro{border-left:3px solid #edb64e;padding-left:20px}.library-title{display:flex;justify-content:space-between;gap:20px;padding:0 0 24px;font-size:14px;border-bottom:1px solid #b8c4cc}article{display:grid;grid-template-columns:48px 1fr;gap:24px;padding:38px 0;border-bottom:1px solid #c9d1d6;scroll-margin-top:24px}blockquote{font:clamp(1.4rem,3.3vw,2rem)/1.5 Georgia,serif;white-space:pre-line;margin:0 0 20px}.number{font:14px/2 monospace;color:var(--accent)}.author{font-weight:600;margin:0}.credit{font-size:14px;color:var(--muted);margin:8px 0 16px}summary{cursor:pointer;font-size:14px;color:var(--accent)}details{font-size:16px}details p{max-width:660px}.permalink{display:inline-block;font-size:14px;margin-top:12px;color:var(--muted)}footer{font-size:14px;color:var(--muted);padding-bottom:70px}footer h2{font-size:18px;color:var(--ink)}:focus-visible{outline:3px solid #bd7619;outline-offset:5px}@media(max-width:600px){header,main,footer{padding:24px}article{grid-template-columns:24px 1fr;gap:12px}nav{flex-wrap:wrap}h1{margin-top:32px}}@media print{details{display:block}nav,.permalink{display:none}article{break-inside:avoid}}
</style></head><body><header><nav><strong>FOR ALL BEINGS</strong><span><a href="#teachings">Read</a> · <a href="archive.json" download>Keep a copy</a> · <a href="https://github.com/gigachadmma69/dharma-for-all-beings">Open source</a></span></nav><h1>A few words.<br>A little less grasping.</h1><p class="intro">Teachings across Buddhist traditions, preserved in their translators’ words. Begin with care; take your time with what follows.</p></header><main id="teachings"><div class="library-title"><strong>THE READING SEQUENCE</strong><span>32 sourced passages</span></div>'''+''.join(rows)+'''</main><footer><h2>A library, not a measure of realization.</h2><p>This reading order is an editorial invitation: compassion, accessible practice, then subtler teachings on emptiness and awareness. Traditions differ. A brief passage does not replace its context, practice, or a teacher.</p><p>New selections enter only after source review. This edition was assembled on 28 September 2026. The website does not generate teachings or autonomously post to X; research and publishing are maintained separately.</p><p>Software is MIT-licensed. Quotations and translations are not relicensed: see <a href="RIGHTS.md">rights and attribution</a>. <a href="archive.json" download>Download the archive</a> to preserve it or help it find another home.</p></footer></body></html>'''
(ROOT/'dist').mkdir(exist_ok=True)
(ROOT/'dist/index.html').write_text(page)
(ROOT/'dist/archive.json').write_text(json.dumps(data,ensure_ascii=False,indent=2)+'\n')
(ROOT/'dist/RIGHTS.md').write_text((ROOT/'RIGHTS.md').read_text())
assert len(rows)==len(data['teachings'])
print(f'Built {len(rows)} sourced teaching entries')
